version: "3.4"

services:
  screenshotter:
    container_name: screenshotter
    build: .
    environment:
      - MAX_SIZE=204800
    ports:
      - 3001:3000
    volumes:
      - ./extracts:/app/extracts
      - ./temp:/app/temp
